name: KillLeaderboard
version: 1.3
main: board.Main
author: Fusion

commands:
  checkKills:
    description: "Checks your total kills"
    usage: "/checkKills"
  createHologram:
    description: "Creates the leaderboard"
    usage: "/createHologram"
  refreshLeaderboard:
    description: "Refreshes the leaderboard"
    usage: "/refreshLeaderboard"
